### ISSUE TITLE
Shutting down due to copyright concerns

### ISSUE THREAD

**Issue by bkf2020** [bkf2020/amcprat-simple#11]
AMCPRAT and AMCPRAT-Simple are being shut down due to copyright concerns. In short, the MAA has copyrighted the AMC/AIME problems, and the projects contain those copyrighted problems.

See https://bkf2020.github.io/blog/amcprat-replacement.html for more information.

The date of the shutdown will be added once amcgen is finished. It is likely going to be 2 weeks after that date.

**Comment by bkf2020** [comment]
Use this code for the announcement

HTML:
```html
<div class="annoucement">
	<h2>IMPORTANT ANNOUCEMENT</h2>
	<p>
		Due to copyright issues AMCPRAT and AMCPRAT-Simple
		are shutting down. They will be closed in 2 weeks after
		this message.
	</p>
</div>
```
CSS:
```css
.annoucement {
	border-color: darkorange;
	border-style: dashed;
	border-radius: 1em;
	margin-top: 2em;
	padding-left: 1em;
	background-color: #e6e5ad;
	color: black;
}
```
